version: '3.9'

services:
  postgres:
    image: postgres:18
    build: .
    container_name: bgl-postgres
    env_file: "db.env"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "7501:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
    restart: always

volumes:
  postgres_data:

